def instructions(init=0, name=""):
	clear()
	if init == 1:
		print("Alright, " + name + " the rules are as follow:\n")
	print("RopasciRPG is a rock-paper-scissors game with RPG elements, as the name sort of implies.\nLet's take it bite for bite.\n")
	print("When you create a new character, you get to choose a name, a gender and a race. As of current version, gender and race will not make a difference in-game (this might change if I make future updates).\nHereafter, you will arrive at the Town Center. This is the \"hub\" of the game, and from here you get to choose what you want to do. The options are:\n1) Look for trouble\n2) Go to \"Ole Apothecary\"\n3) Go to \"Ye Smithe o'er All\"\n4) Save game\n5) Exit to main menu\n")
	print("1) Look for trouble\nLook for trouble initiates a fight. You will meet an NPC that is the same level as you, and you will get to fight him. You have a single chance to flee from your opponent, but there's only a 40 percent chance of success. Failing will force you to fight the opponent.\n")
	input("> (Press enter for next page)")
	clear()
	print("2) Go to \"Ole Apothecary\"\nThe \"Ole Apothecary\" is the medical shop of the town. Here, you can buy Health Potions and Health Potions. How it works is pretty self-explanatory.\n")
	print("3) Go to \"Ye Smithe o'er All\"\nThe \"Ye Smithe o'er All\" is the town's blacksmith. Here, you get to upgrade your weapons to their next tier.\n")
	print("4) Save game\nThis option is pretty self-explanatory. You get to save your game, so you can return to it later. Please check that after you have saved, a \"saves\" folder with the chosen name exists next to the .py file. If not, perhaps some permissions are off.\n")
	print("5) Exit to main menu\nThis options puts you back to the main menu. But don't worry, it asks you if you're sure before doing so.")
	input("> (Press enter for next page)")
	clear()
	print("Fighting:\nA fight is a normal rock-paper-scissors duel as you would expect it. Rock beats scissors, scissors beat paper, paper beats rock.\nA fight is a battle between an NPC and you as the player. It ends when either of you hit 0HP.\nWhen you initiate in a fight, you get 4 options. They are:\n1) Rock\n2) Paper\n3) Scissors\n4) Use item\n\nYou simply select the weapon that you wish to use, and then you get to know whether you, in this turn, beat the opponent or not.\nIf you hit, you damage the amount of damage that your current weapon deals. In the beginning, this will be 1HP, but as you upgrade your weapons, you get to deal more damage.\nPlease note that an upgraded weapon in a particular weapon-type does not win over a non-upgraded weapon in it's defeating type.\nFor example: A tier 2 rock-type weapon will not beat a tier 1 paper-type weapon, as paper beats rock.")
	input("> (Press enter for next page)")
	clear()
	print("4) Use items\nThis will open a menu where you can select and use your items. In the current version, you can only buy Health Potions, so you could call the inventory a potion bag. Whatever. Also, everyone starts with 1 Health Potion.\n")
	print("Lives:\nIn RopasciRPG you start with 3 lives. This is the amount of times you're allowed to lose a fight. If your lives reach 0, you die. But, don't despair, whenever you level up, your lives go back up to full again!")
	input("> (Press enter for next page)")
	clear()
	print("Leveling:\nYou level once you reach the amount of experience points required for the next level. You can always see how many experience points you have, and how many you need, in the Town Center.\nLeveling up gives you 2 more HP, and unlocks new weapon upgrades. The max level is 3.\n")
	print("How is exp calculated?\nIt is simple. You get the amount of total HP your opponent had, multiplied by 2. So, if you're in level 1, you will always get 6 exp for beating the opponent. Level 2 is 10 exp and so on and so forth.\n")
	print("How is gold calculated? And what is gold?\nThere are two factors which determine how many gold you win from a fight. These two factors added together and then adding 2 on top of that gives you your earned gold.\nFactor 1: Your remaining HP at the end of a fight, multiplied by 2. So, if you end the fight with 4HP, you get 4 gold from that. If you end it with 1HP, you get 1 gold from that factor.\nFactor 2: The opponent's level. So, if you fight against a level 1 Thug, you get 1 gold from that factor. And then, as mentioned, we add 2 to that value to get the final earned gold.")
	input("> (Press enter for last page)")
	clear()
	print("What are the weapon tiers?\nRock-type:\nTier 1: Rock\nTier 2: Boulder\nTier 3: Anvil\n\nPaper-type:\nTier 1: Paper\nTier 2: Tinfoil\nTier 3: Duct Tape\n\nScissors-type:\nTier 1: Scissors\nTier 2: Knife\nTier 3: Sword\n")
	print("Anything else I need to know?\nI don't think so. If you experience any bugs, let me know over at GitHub.\n\nHave fun!")
	if init == 1:
		input("> (Press enter to go to character creation)")
		ng2(name)
	else:
		input("> (Press enter to return to the main menu)")
		initiate()